name: fireworks_counter
description: Modified Flutter counter template app with fireworks.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

  fireworks:
    path: ../fireworks

flutter:
  uses-material-design: true
