name: Checks

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/checks.yml'
      - '**/lib/**'
      - '**/android/**'
      - '**/ios/**'
      - '**/web/**'
      - '**/macos/**'
      - '**/windows/**'
      - '**/pubspec.yaml'
      - '**/test/**'
      - '**/assets/**'

jobs:
  analyze:
    timeout-minutes: 7
    runs-on: ubuntu-latest
    name: Analysis of ${{ matrix.package }} (${{ matrix.channel }})
    strategy:
      matrix:
        channel:
          # Exlcuding stable until web support reaches the stable channel.
          # - 'stable'
          - 'beta'
          - 'dev'
        package:
          - 'fireworks'
          - 'fireworks_counter'
          - 'fireworks_demo'
          - 'fireworks_gif'
      fail-fast: false

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: subosito/flutter-action@v1.4.0
        with:
          channel: ${{ matrix.channel }}
      - run: flutter pub get
        working-directory: ${{ matrix.package }}
      - name: Check format
        working-directory: ${{ matrix.package }}
        run: dart format . --fix --set-exit-if-changed
      - run: flutter analyze
        working-directory: ${{ matrix.package }}
