name: checks

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/checks.yml'
      - '**/lib/**'
      - '**/android/**'
      - '**/ios/**'
      - '**/web/**'
      - '**/macos/**'
      - '**/windows/**'
      - '**/pubspec.yaml'
      - '**/test/**'
      - '**/assets/**'

jobs:
  analyze:
    timeout-minutes: 7
    runs-on: ubuntu-latest
    name: ${{ matrix.package }} analysis on ${{ matrix.channel }}
    strategy:
      matrix:
        channel:
          - 'stable'
          - 'beta'
          - 'master'
        package:
          - 'fireworks'
          - 'fireworks_counter'
          - 'fireworks_demo'
      fail-fast: false
    env:
      working-directory: ${{ matrix.package }}

    steps:
      - uses: actions/checkout@v2.3.5
      - uses: subosito/flutter-action@v1.5.3
        with:
          channel: ${{ matrix.channel }}
      - name: pub get
        run: flutter pub get
        working-directory: ${{ env.working-directory }}
      - name: dart format
        run: dart format . --fix --set-exit-if-changed
        working-directory: ${{ env.working-directory }}
      - run: dart analyze
        working-directory: ${{ env.working-directory }}
